// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebNetCoreWithReact.Data;

namespace WebNetCoreWithReact.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WebNetCoreWithReact.Models.Daprt", b =>
                {
                    b.Property<int>("DepartNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Departname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Locations")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartNumber");

                    b.ToTable("Daprt");

                    b.HasData(
                        new
                        {
                            DepartNumber = 1,
                            Departname = "Sofia",
                            Locations = "Airport Terminal 1"
                        },
                        new
                        {
                            DepartNumber = 2,
                            Departname = "Sofia",
                            Locations = "Airport Terminal 2"
                        },
                        new
                        {
                            DepartNumber = 3,
                            Departname = "Plovdiv",
                            Locations = "Novotel"
                        },
                        new
                        {
                            DepartNumber = 4,
                            Departname = "Stara Zagora",
                            Locations = "Stadium Beroe"
                        },
                        new
                        {
                            DepartNumber = 5,
                            Departname = "Shumen",
                            Locations = "Post Office"
                        },
                        new
                        {
                            DepartNumber = 6,
                            Departname = "Burgas",
                            Locations = "Post Office"
                        },
                        new
                        {
                            DepartNumber = 7,
                            Departname = "Varna",
                            Locations = "Dolphinarium"
                        },
                        new
                        {
                            DepartNumber = 8,
                            Departname = "Pleven",
                            Locations = "Hotel Bulgaria"
                        },
                        new
                        {
                            DepartNumber = 9,
                            Departname = "Sozopol",
                            Locations = "Old City Post Office"
                        },
                        new
                        {
                            DepartNumber = 10,
                            Departname = "Lovech",
                            Locations = "Varosha Gallery"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
